try:
    print("Inside try")
except NameError:
    print("Found error")
else:
    print("Else block")